// web/src/app/[locale]/panel/components/StudyPreview.tsx
import { Study } from "@/lib/types/models/study";
import IconWeb from "~icons/mdi/web";
import IconLink from "~icons/mdi/external-link";

export default function StudyPreview({ study }: { study: Study }) {
  return (
    <div>
      <p className="font-semibold">{study.name}</p>
      <p>{study.description}</p>
      <div className="flex items-center gap-1 py-0.5 mt-1 detail">
        <IconWeb />
        <span>{new URL(study.websiteUrl).host}</span>
        <IconLink />
      </div>
    </div>
  );
}

// web/src/lib/panel/StudyPreview.svelte
<script lang="ts">
  import type { Study } from "$lib/types/models/study";
  import Icon from "@iconify/svelte";

  export let study: Study;
</script>

<div>
  <p class="font-semibold">{study.name}</p>
  <p>{study.description}</p>
  <a href={study.websiteUrl} target="_blank" class="inline-block mt-1">
    <div class="flex items-center gap-1 py-0.5 detail">
      <Icon icon="mdi:web" />
      <span>{new URL(study.websiteUrl).host}</span>
      <Icon icon="mdi:external-link" />
    </div>
  </a>
</div>
