// web/src/components/LanguageButton.tsx
"use client";

import { useTranslations } from "next-intl";
import { useState } from "react";
import IconLanguage from "~icons/tabler/language";
import LanguageModal from "./LanguageModal";

export default function LanguageButton() {
  const t = useTranslations();
  const [isModalShown, showModal] = useState(false);

  return (
    <>
      <button
        className="setting"
        aria-label={t("common.nav.controls.settings_lang")}
        onClick={() => showModal(true)}
      >
        <IconLanguage className="text-xl icon-highlight-stroke" />
      </button>
      <LanguageModal isShown={isModalShown} onClose={() => showModal(false)} />
    </>
  );
}

// web/src/lib/controls/LanguageButton.svelte
<script lang="ts">
  import LanguageDialog from "$lib/dialogs/LanguageDialog.svelte";
  import Icon from "@iconify/svelte";

  import { _ } from "svelte-i18n";

  let showDialog = false;
</script>

<button
  class="setting"
  aria-label={$_("nav.controls.settings_lang")}
  on:click={() => (showDialog = true)}
>
  <Icon icon="tabler:language" width="32" />
</button>

<LanguageDialog isOpen={showDialog} onDismiss={() => (showDialog = false)} />
