// web/src/app/[locale]/panel/components/LanguageButton.tsx
import { useTranslations } from "next-intl";
import IconLanguage from "~icons/tabler/language";

export default function LanguageButton() {
  const t = useTranslations();

  return (
    <button
      className="setting"
      aria-label={t("nav.controls.settings_lang")}
      //   on:click={() => (showDialog = true)}
    >
      <IconLanguage className="text-xl" />
    </button>
  );
}

// web/src/lib/controls/LanguageButton.svelte
<script lang="ts">
  import LanguageDialog from "$lib/dialogs/LanguageDialog.svelte";
  import Icon from "@iconify/svelte";

  import { _ } from "svelte-i18n";

  let showDialog = false;
</script>

<button
  class="setting"
  aria-label={$_("nav.controls.settings_lang")}
  on:click={() => (showDialog = true)}
>
  <Icon icon="tabler:language" width="32" />
</button>

<LanguageDialog isOpen={showDialog} onDismiss={() => (showDialog = false)} />
