// web/src/app/[locale]/panel/page.tsx
import { useTranslations } from "next-intl";
import IconLabel from "@/components/IconLabel";
import Link from "next/link";

export default function Root() {
  const t = useTranslations();

  return (
    <>
      <h1 className="cta">
        {t("panel.welcome.message", { action: t("panel.welcome.button") })}
      </h1>
      <Link href="start" className="action action-primary inline-block">
        <IconLabel caption={t("panel.welcome.button")} />
      </Link>
    </>
  );
}

// web/src/routes/panel/+page.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import IconLabel from "$lib/IconLabel.svelte";
</script>

<h1 class="cta">
  {$_("panel.welcome.message", {
    values: { action: $_("panel.welcome.button") },
  })}
</h1>
<a href="/panel/start" class="action action-primary inline-block">
  <IconLabel caption={$_("panel.welcome.button")} />
</a>
