// web/src/lib/controls/A11yButton.svelte
<script lang="ts">
  import Icon from "@iconify/svelte";

  import { _ } from "svelte-i18n";
</script>

<button
  class="p-2 focus:outline-gray-300 dark:focus:outline-gray-400 rounded-md focus:outline"
  aria-label={$_("nav.controls.settings_a11y")}
>
  <Icon icon="radix-icons:accessibility" width="32" />
</button>

// web/src/app/[locale]/panel/components/A11yButton.tsx
import { useTranslations } from "next-intl";
import IconAccessibility from "~icons/radix-icons/accessibility";

export default function A11yButton() {
  const t = useTranslations();

  return (
    <button className="setting" aria-label={t("nav.controls.settings_a11y")}>
      <IconAccessibility className="text-xl" />
    </button>
  );
}
