// web/src/lib/controls/HelpButton.svelte
<script lang="ts">
  import IconLabel from "$lib/IconLabel.svelte";
  import { helpText } from "$lib/modules/help";
  import { _ } from "svelte-i18n";

  export let text: string;

  function showHelp() {
    helpText.set(text);
  }
</script>

<button class="action" on:click={showHelp}>
  <IconLabel caption={$_("a11y.help")} icon="lucide:help-circle" />
</button>

// web/src/app/[locale]/panel/components/HelpButton.tsx
"use client";

import { useTranslations } from "next-intl";
import IconLabel from "@/components/IconLabel";
import IconHelp from "~icons/lucide/help-circle";

export default function HelpButton({}: { text: string }) {
  const t = useTranslations();

  function showHelp() {}

  return (
    <button className="action" onClick={showHelp}>
      <IconLabel caption={t("common.a11y.help")} icon={<IconHelp />} />
    </button>
  );
}
