// web/src/lib/controls/HelpButton.svelte
<script lang="ts">
  import IconLabel from "$lib/IconLabel.svelte";
  import { helpText } from "$lib/modules/help";
  import { _ } from "svelte-i18n";

  export let text: string;

  function showHelp() {
    helpText.set(text);
  }
</script>

<button class="action" on:click={showHelp}>
  <IconLabel caption={$_("a11y.help")} icon="lucide:help-circle" />
</button>

// web/src/app/[locale]/research/components/HelpButton.tsx
"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import IconLabel from "@/components/IconLabel";
import IconHelp from "~icons/lucide/help-circle";
import Modal from "@/components/Modal";

export default function HelpButton({ text }: { text: string }) {
  const t = useTranslations();
  const [isHelpShown, showHelp] = useState(false);

  return (
    <>
      <button className="action" onClick={() => showHelp(true)}>
        <IconLabel caption={t("common.a11y.help")} icon={<IconHelp />} />
      </button>
      <Modal
        title={t("common.a11y.help")}
        isOpen={isHelpShown}
        onClose={() => showHelp(false)}
      >
        {text}
      </Modal>
    </>
  );
}
