// web/src/routes/panel/start/+page.svelte
<script lang="ts">
  import HelpButton from "$lib/controls/HelpButton.svelte";
  import StudyPreview from "$lib/panel/StudyPreview.svelte";
  import type { Study } from "$lib/types/models/study";
  import { _ } from "svelte-i18n";

  const studies: Study[] = [
    {
      id: "test",
      name: "Test",
      description: "This is a test study.",
      websiteUrl: "https://example.com",
    },
  ];
</script>

<h1 class="cta">{$_("panel.studies_avail")}</h1>
<ul class="max-w-md m-auto space-y-2">
  {#each studies as study}
    <li>
      <a href="/panel/study/{study.id}" class="block action action-li">
        <StudyPreview {study} />
      </a>
    </li>
  {/each}
</ul>
<div class="mt-4">
  <HelpButton text={$_("panel.help.select_study")} />
</div>

// web/src/app/[locale]/panel/start/page.tsx
import Link from "next/link";
import { useTranslations } from "next-intl";
import { Study } from "@/lib/types/models/study";
import StudyPreview from "../components/StudyPreview";
import HelpButton from "../components/HelpButton";

export default function Root() {
  const t = useTranslations();

  const studies: Study[] = [
    {
      id: "test",
      name: "Test",
      description: "This is a test study.",
      websiteUrl: "https://example.com",
    },
  ];

  return (
    <>
      <h1 className="cta">{t("panel.studies_avail")}</h1>
      <ul className="max-w-md m-auto space-y-2">
        {studies.map((study, key) => (
          <li key={key}>
            <Link
              href={`../study/${study.id}`}
              className="block action action-li"
            >
              <StudyPreview study={study} />
            </Link>
          </li>
        ))}
      </ul>
      <div className="mt-4">
        <HelpButton text={t("panel.help.select_study")} />
      </div>
    </>
  );
}
